version: '3.8'

services:
  mysql-db:
    image: mysql:8.1
    container_name: hackaton-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password23
      MYSQL_DATABASE: hack
      MYSQL_USER: hack
      MYSQL_PASSWORD: Password23
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hackaton-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pPassword23" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackaton-app
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - hackaton-network

volumes:
  mysql-data:

networks:
  hackaton-network:
